# Generated by Django 6.0.7 on 2026-08-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Select Product', 'Select Product'), ('Ball', 'Ball'), ('Bags & Caps', 'Bags & Caps'), ('Socks', 'Socks'), ('Compressions', 'Compressions'), ('Footwears', 'Footwears'), ('Gloves', 'Gloves'), ('Sport Shoes', 'Sport Shoes'), ('Hoodies', 'Hoodies'), ('Shirts', 'Shirts'), ('Casual Shoes', 'Casual Shoes'), ('Watches', 'Watches'), ('Laptops', 'Laptops'), ('Households', 'Households')], default='Select Product', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sports',
            field=models.CharField(blank=True, choices=[('Select Sport', 'Select Sport'), ('Basketball🏀', 'Basketball🏀'), ('Boxing🥊', 'Boxing🥊'), ('Badmington🏸', 'Badmington🏸'), ('Gym⛹', 'Gym⛹'), ('Soccer⚽ ', 'Soccer⚽ '), ('Tracks & Fields🏃', 'Tracks & Fields🏃'), ('Rugby🏉', 'Rugby🏉'), ('Volleyball🏐', 'Volleyball🏐'), ('Ping Pong🎾', 'Ping Pong🎾'), ('Cricket', 'Cricket'), ('Tennis🎾', 'Tennis🎾')], default='Select Sports', max_length=30, null=True),
        ),
    ]
