# Generated by Django 5.2.7 on 2026-06-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='sales_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_type',
            field=models.CharField(blank=True, choices=[('New', 'Brand New'), ('Hot', 'Trending'), ('Acube', 'Grade A Used')], default='', max_length=7, null=True),
        ),
    ]
