# Generated by Django 5.2.7 on 2026-06-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_sale_price_product_sales_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_type',
            field=models.CharField(blank=True, choices=[('New', 'Brand New'), ('Hot', 'Trending'), ('Acube', 'Pristine')], default='', max_length=7, null=True),
        ),
    ]
