# Generated by Django 6.0.7 on 2026-08-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_category_alter_product_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='import_category',
            field=models.CharField(blank=True, choices=[('UK Import', 'UK Import'), ('US Import', 'US Import'), ('China Import', 'China Import')], default='Select Import', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Select Product', 'Select Product'), ('Ball', 'Ball'), ('Bags & Caps', 'Bags & Caps'), ('Socks', 'Socks'), ('Compressions', 'Compressions'), ('Footwears', 'Footwears'), ('Gloves', 'Gloves'), ('Sport Shoes', 'Sport Shoes'), ('Hoodies', 'Hoodies'), ('Shirts', 'Shirts'), ('Casual Shoes', 'Casual Shoes'), ('Watches', 'Watches'), ('Laptops', 'Laptops'), ('Households', 'Households'), ('leather_work', 'Leather Work / Handmade Products'), ('bale_material', 'Bale Materials'), ('general', 'General')], default='Select Product', max_length=15, null=True),
        ),
    ]
