# Generated by Django 6.0.7 on 2026-08-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_import_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_type',
            field=models.CharField(blank=True, choices=[('New', 'Brand New'), ('Hot', 'Trending'), ('Acube', 'Pristine')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Ball', 'Ball'), ('Bags & Caps', 'Bags & Caps'), ('Socks', 'Socks'), ('Compressions', 'Compressions'), ('Footwears', 'Footwears'), ('Gloves', 'Gloves'), ('Sport Shoes', 'Sport Shoes'), ('Hoodies', 'Hoodies'), ('Shirts', 'Shirts'), ('Casual Shoes', 'Casual Shoes'), ('Watches', 'Watches'), ('Laptops', 'Laptops'), ('Households', 'Households'), ('leather_work', 'Leather Work / Handmade Products'), ('bale_material', 'Bale Materials'), ('general', 'General')], default='General', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender_type',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Male', 'Male'), ('Female', 'Female')], default='General', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sports',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Basketball🏀', 'Basketball🏀'), ('Boxing🥊', 'Boxing🥊'), ('Badmington🏸', 'Badmington🏸'), ('Gym⛹', 'Gym⛹'), ('Soccer⚽ ', 'Soccer⚽ '), ('Tracks & Fields🏃', 'Tracks & Fields🏃'), ('Rugby🏉', 'Rugby🏉'), ('Volleyball🏐', 'Volleyball🏐'), ('Ping Pong🎾', 'Ping Pong🎾'), ('Cricket', 'Cricket'), ('Tennis🎾', 'Tennis🎾')], default='General', max_length=30, null=True),
        ),
    ]
