# Generated by Django 6.0.7 on 2026-08-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_brand_type_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Ball', 'Ball'), ('Bags & Caps', 'Bags & Caps'), ('Socks', 'Socks'), ('Compressions', 'Compressions'), ('Footwears', 'Footwears'), ('Gloves', 'Gloves'), ('Sport Shoes', 'Sport Shoes'), ('Hoodies', 'Hoodies'), ('Shirts', 'Shirts'), ('Casual Shoes', 'Casual Shoes'), ('Watches', 'Watches'), ('Laptops', 'Laptops'), ('Households', 'Households'), ('leather_work', 'Leather Work / Handmade Products'), ('bale_material', 'Bale Materials'), ('bedsheets', 'Bedsheets')], default='General', max_length=15, null=True),
        ),
    ]
