# Generated by Django 5.2.7 on 2026-06-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='type',
            new_name='competition_type',
        ),
        migrations.AlterField(
            model_name='competition',
            name='opponents',
            field=models.ManyToManyField(blank=True, to='team.opponent'),
        ),
    ]
