# Generated by Django 5.2.7 on 2026-06-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_shotcharts_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shotcharts',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='game_chart',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Game_Chart/'),
        ),
    ]
