# Generated by Django 5.2.7 on 2026-06-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_type_competition_competition_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='award_year',
        ),
        migrations.RemoveField(
            model_name='player',
            name='career_awards',
        ),
        migrations.AddField(
            model_name='careerrecords',
            name='award_year',
            field=models.CharField(blank=True, default='2026', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='careerrecords',
            name='career_awards',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
