# Generated by Django 5.2.7 on 2026-06-22 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_player_award_year_remove_player_career_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatline',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team', to_field='slug'),
        ),
    ]
