# Generated by Django 5.2.7 on 2026-06-30 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_shotcharts_game_game_game_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='award_year',
            field=models.CharField(blank=True, default='2026', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='awards',
            name='career_awards',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='awards',
            name='player_award',
            field=models.ForeignKey(blank=True, help_text='The player associated with awards.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_awards', to='team.player'),
        ),
        migrations.AddField(
            model_name='awards',
            name='team_award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_trophy', to='team.team'),
        ),
    ]
