# Generated by Django 5.2.7 on 2026-07-29 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_awards_award_year_awards_career_awards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title if blank', null=True, unique=True)),
                ('youtube_url', models.URLField(help_text='Paste the YouTube watch or embed URL')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='team.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_highlights', to='team.player')),
            ],
            options={
                'verbose_name_plural': 'Game Highlights',
            },
        ),
    ]
