# Generated by Django 5.2.7 on 2026-07-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_gamehighlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehighlight',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube URL'),
        ),
    ]
