# Generated by Django 6.0.7 on 2026-08-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_gamehighlight_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='email',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='slug',
        ),
    ]
